############################################################
#  INFORMATION GÉNÉRALE
############################################################
title       : "Project of Paul"
email       : "paul.david130305@gmail.com"
description : >-
  This site is for the person who wants to learn and discover
  a lot of things about “Innovation and Invention”.

# URL publiques — adapte uniquement les lignes ci-dessous
url     : "https://inventorlearn.github.io"   # domaine sans slash final
baseurl : "/inventorlearn"                                  # "/inventorlearn" si le dépôt ≠ *.github.io

# Profils sociaux affichés par le thème « minima »
youtube_username : "Inventorlearn"
github_username  : "Inventorlearn"

############################################################
#  CONSTRUCTION DU SITE
############################################################
theme   : minima

plugins :
  - jekyll-feed          # flux RSS/Atom auto

############################################################
#  COLLECTIONS PERSONNALISÉES
############################################################
collections :
  projets :
    output    : true
    permalink : /projets/:path/
  cours :
    output    : true
    permalink : /cours/:name/

############################################################
#  OPTIONS SASS (supprime les warnings de dépendances)
############################################################
sass :
  quiet_deps : true
