############################################################
#  INFORMATION GÉNÉRALE
############################################################
title       : "Project of Paul"
email       : "paul.david130305@gmail.com"
description : >-
  This site is for the person who wants to learn and discover
  a lot of things about “Innovation and Invention”.

# URL publiques — adapte uniquement les lignes ci-dessous
url     : "https://inventorlearn.github.io"   # domaine sans slash final
baseurl : "/inventorlearn"                                  # "/inventorlearn" si le dépôt ≠ *.github.io

# Profils sociaux affichés par le thème « minima »
youtube_username : "Inventorlearn"
github_username  : "Inventorlearn"

############################################################
#  CONSTRUCTION DU SITE
############################################################
remote_theme : "mmistakes/minimal-mistakes"

plugins :
  - jekyll-feed          # flux RSS/Atom auto
  - jekyll-include-cache
 
############################################################
#  NAVIGATION DU BANDEAU
############################################################
  header_pages:
    - index.md
    - _pages/projets.md
    - _pages/cours.md
	
############################################################
#  APPARENCE RAPIDE
############################################################
  minimal_mistakes_skin : "air"   # tu pourras essayer "dark", "sunrise", etc.
  search : true
  