############################################################
#  INFORMATIONS GÉNÉRALES
############################################################
title       : "Project of Paul"
email       : "paul.david130305@gmail.com"
description : >-
  This site is for the person who wants to learn and discover
  a lot of things about “Innovation and Invention”.

url     : "https://inventorlearn.github.io"   # sans "/" final
baseurl : "/inventorlearn"                    # vide ("") si ton dépôt devient inventorl​earn.github.io

# Profils sociaux
youtube_username : "Inventorlearn"
github_username  : "Inventorlearn"

############################################################
#  CONSTRUCTION DU SITE
############################################################
remote_theme : "mmistakes/minimal-mistakes"

plugins :
  - jekyll-feed
  - jekyll-include-cache

############################################################
#  NAVIGATION DU BANDEAU (menu du haut)
############################################################
header_pages :
  - index.md
  - _pages/projets.md
  - _pages/cours.md

############################################################
#  APPARENCE RAPIDE
############################################################
minimal_mistakes_skin : "air"     # essais : "default", "dark", "sunrise", ...
search                : true      # active la loupe de recherche
